name: food_app
description: A new Flutter application.


environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  rtmp_publisher:
    path: ../

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  animated_text_kit: ^2.2.0
  modal_progress_hud: ^0.1.3
  http: ^0.12.2
  #firebase_auth: ^0.20.1
  #cloud_firestore: ^0.16.0
 #firebase_core: ^0.7.0
  #firebase_core_platform_interface: ^3.0.1
  #firebase_messaging: ^8.0.0-dev.14
  #firebase_auth_web: ^0.3.3
  carousel_slider: ^2.2.1
  percent_indicator: "^2.1.5"
  polygon_clipper: ^1.0.2
  flutter_recaptcha_v2: ^0.1.0
  webview_flutter: ^0.3.22+1
  youtube_player_flutter: ^7.0.0+7
  image_picker: ^0.6.7+11
  cached_network_image: ^2.3.2+1
  share: ^0.6.5+3
  dio: ^3.0.10
  stripe_payment: ^1.0.6
  dropdownfield: 1.0.0
  autocomplete_textfield: ^1.7.3
  searchable_dropdown: ^1.1.3
  random_color: ^1.0.5
  pie_chart: ^4.0.1
  syncfusion_flutter_calendar: ^18.3.51
  flutter_clean_calendar: ^1.0.2+1
  intl: ^0.16.1
  barcode_scan: ^3.0.1
  story_view: ^0.11.4
  #agora_rtc_engine: ^3.1.2
  permission_handler: ^3.0.0
  flutter_web_browser: ^0.13.1
  shared_preferences: ^0.5.12+4
  date_time_picker: ^1.1.1
  ext_video_player: ^0.0.4
  path_provider: ^1.6.8
  #video_player: ^0.10.11
  video_player: ^0.10.2+3
  e2e: ^0.4.2
  wakelock: ^0.1.4+1
  google_sign_in: ^4.5.0
  #timezone: ^0.5.9
  #language_pickers: ^0.2.0+1
  #camera_with_rtmp: ^0.3.2
  rflutter_alert: ^1.1.0
  flutter_incall: ^1.0.0
  fijkplayer: ^0.8.7
  #flutter_video_cast: ^1.0.3
  #flutter_barcode_scanner: ^1.0.1
  exif:


dev_dependencies:
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: openSan
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 500
  assets:
    - images/